apiVersion: v1
kind: PersistentVolume
metadata:
  name: submarine-database-pv
spec:
  storageClassName: "submarine-storageclass"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/database"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: submarine-server-pv
spec:
  storageClassName: "submarine-storageclass"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/server"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: submarine-mlflow-pv
spec:
  storageClassName: "submarine-storageclass"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mlflow"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: submarine-minio-pv
spec:
  storageClassName: "submarine-storageclass"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minio"
